 export const casedata = [
    {
        "title":"January",
        "completed":120,
        "uncompleted":30
    },
    {
        "title":"Feburary",
        "completed":50,
        "uncompleted":10
    },
    {
        "title":"March",
        "completed":114,
        "uncompleted":5
    },
    {
        "title":"April",
        "completed":120,
        "uncompleted":30
    }
]